### ISSUE TITLE
Emission counter increases, even though only green energy is bought

### ISSUE THREAD

**Issue by Nolle10** [mathiasgredal/1-Semesterprojekt-Civil-Gruppe-5.2#26]
#25 You can see it printed, if you only buy green energy, the emission counter will increase in the nextyear window.

**Comment by mathiasgredal** [comment]
That is your internal combustion car and gas heater I think

**Comment by Nolle10** [comment]
So I'm stupid, didn't think about our energy consumers, that is what causes the increase in emission.

**Comment by Nolle10** [comment]
> That is your internal combustion car and gas heater I think

You are right, and I'm stupid 😂
