### ISSUE TITLE
Problems with merging #25 into the master

### ISSUE THREAD

**Issue by Nolle10** [mathiasgredal/1-Semesterprojekt-Civil-Gruppe-5.2#28]
#25 didn't merge properly, I may need some help with getting all the features from the #23 and #24 into the merge, so it doesn't begin to delete your work @mathiasgredal

**Comment by mathiasgredal** [comment]
I will look at it

**Comment by mathiasgredal** [comment]
Merged with master in add-gui-functionality-2, if you can confirm that I have not removed some of your code, then i can open a pull request.

**Comment by mathiasgredal** [comment]
Nevermind

**Comment by mathiasgredal** [comment]
This branch is a train wreck

**Comment by mathiasgredal** [comment]
I almost died, can you check branch add-gui-functionality-4 and confirm that i didn't overwrite some of your changes.

**Comment by Nolle10** [comment]
@mathiasgredal How do you do it???? always fixing shit
